#!/bin/sh
LIBRARY_PATH="/mnt/Videos"

find $LIBRARY_PATH \( -name '*.mkv' -or -name '*.mp4' \) -print0 | xargs -0 -I {} sh -c 'ffmpeg -ss 180 -t 3 -i "{}" \
	-vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
	-loop 0 "static/img/$(basename "{}").gif"'
